#pragma once

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 400

// TEX ID
#define TEX_DEMOOBJECT 100
#define TEX_DEMOENEMY 200
#define PLAYER_RUN_VELOCCITY 500

// keyBoard
#define DOWN_ARROW DIK_DOWNARROW
#define UP_ARROW DIK_UPARROW
#define LEFT_ARROW DIK_LEFTARROW
#define RIGHT_ARROW DIK_RIGHTARROW
#define JUMP_ARROW DIK_D
#define ATTACK_ARROW DIK_S


// SCENE ID
#define DEMO_SCENE 1

// GRID
#define GRID_COLUMN_NUMBERS 100
#define GRID_ROW_NUMBERS 100


// state speed
#define RUN_SPEED 100
#define JUMP_SPEED 200
#define SLIDE_SPEED 50
#define MAX_JUMP 150

