#pragma once

#define SCREEN_WIDTH 600
#define SCREEN_HEIGHT 400

#define TEX_DEMOOBJECT 100
#define PLAYER_RUN_VELOCCITY 100

#define DOWN_ARROW DIK_S
#define UP_ARROW DIK_W
#define LEFT_ARROW DIK_D
#define RIGHT_ARROW DIK_A
#define SLASH_BUTTON DIK_G
#define JUMP_BUTTON DIK_H