#pragma once

//#define SCREEN_WIDTH 2256
//#define SCREEN_HEIGHT 1136
#define SCREEN_WIDTH 318
#define SCREEN_HEIGHT 230

#define INDEX_CAMERA_WIDTH 30
#define INDEX_CAMERA_HEIGHT 20
#define VELOCITY_CAMERA 3

#define FPS 60
#define SPF 1.0f/FPS

// TEX ID
#define TEX_DEMOOBJECT 100
#define TEX_DEMOENEMY 200
#define TEX_APPLE APPLE
#define TEX_HEART BLUEHEART
#define TEX_GEM GEM
#define TEX_GENIETOKEN GENIETOKEN
#define TEX_BLUEVASE BLUEVASE
#define TEX_STONE STONE
#define TEX_BALL BALL
#define TEX_SPIKE SPIKE
#define TEX_EXITPORT EXITPORT

#define TEX_BAT BAT
#define TEX_SKELETON SKELETON
#define TEX_THINGUARD THINGUARD
#define TEX_FATGUARD FATGUARD
#define TEX_CHAINEDPILLAR CHAINEDPILLAR
#define TEX_PILLAR CHAINEDPILLAR

#define PLAYER_RUN_VELOCCITY 500

// keyBoard
#define DOWN_ARROW DIK_DOWNARROW
#define UP_ARROW DIK_UPARROW
#define LEFT_ARROW DIK_LEFTARROW
#define RIGHT_ARROW DIK_RIGHTARROW
#define JUMP_ARROW DIK_D
#define ATTACK_ARROW DIK_S
#define THROW_ARROW DIK_A


// SCENE ID
#define DEMO_SCENE 1

// GRID
#define GRID_ROW_NUMBERS 30
#define GRID_COLUMN_NUMBERS 60


// state speed
#define RUN_SPEED 120
#define JUMP_SPEED 180
#define SLIDE_SPEED 50
//#define MAX_JUMP 90
#define MAX_JUMP 78
#define CLIMB_SPEED 130


//
enum Tag {
	BAT,
	SKELETON,
	THINGUARD,
	FATGUARD,
	PEDDLER,
	CARPET,
	JAFAR,
	APPLE,
	BLUEHEART,
	GEM,
	GENIETOKEN,
	BLUEVASE,
	STONE,
	BALL,
	SPIKE,
	EXITPORT,
	GROUND,
	WALL,
	CHAINE,
	CHAINEDPILLAR,
	PILLAR1,
	PILLAR2,
	PILLAR3,
	PILLAR4,
	PLAYER,
	NONE
};

enum Layer {
	PlayerType,
	EnemyType,
	ItemType,
	ObstaclesType,	// Chuong ngai vat
	StaticType,
	Surface,
	NoneType
};

